### ISSUE TITLE
`pr-preview`: causes a workflow to fail if it runs outside of a PR

### ISSUE THREAD

**Issue by filoozom** [ethersphere/swarm-actions#26]
If the `pr-preview` action is ran outside of a pull request, it causes the workflow to fail.

One solution could be to add: `if: github.event_name == 'pull_request'` to every step, but that would be messy.

Another solution would be to have a second action (maybe a child one, i.e. `swarm-actions/pr-preview/child`) and have the parent one call that based on a condition.

For now, I'd suggest adding some documentation so that users set the condition themselves:
```yaml
- uses: filoozom/swarm-actions/pr-preview@v1
  if: github.event_name == 'pull_request'
  with:
    ...
```

Related:  https://github.com/actions/runner/issues/662
